name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'
      - '**/*.html'
      - '**/*.json'
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境是最新版本的 Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx，用于构建多平台镜像

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # 缓存 Docker 镜像构建层，加快构建速度
          key: ${{ runner.os }}-docker-${{ github.sha }}  # 缓存的 key
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Dockerfile 的路径
          push: true  # 推送到 Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/a5toa4:latest  # 替换为你的 Docker Hub 仓库名称

      - name: Logout from Docker Hub
        run: docker logout
